services:
  discord-bot-1:
    build: .
    container_name: discord-esquie-bot-1
    env_file:
      - .env1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # discord-bot-2:
  #   build: .
  #   container_name: discord-esquie-bot-2
  #   env_file:
  #     - .env2
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"